# Generated by Django 3.2.7 on 2021-11-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('birth', models.DateField()),
                ('phone', models.BigIntegerField(max_length=15)),
                ('other_contact', models.BigIntegerField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], default='Other', max_length=7)),
                ('role', models.CharField(choices=[('CL', 'Cliente'), ('AD', 'Administrador')], default='Cliente', max_length=14)),
                ('active', models.BooleanField(default=False)),
                ('payment_ok', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
